export const Topicarray1: string[] = [
  "Spark",
  "Databricks",
  "DataFrames",
  "RDDs",
  "PySpark",
  "Spark SQL",
  "MLlib",
  "Spark Streaming",
  "Data Pipelines",
  "Cluster Management",
  "Fault Tolerance",
  "Parallel Processing",
  "Big Data",
  "Apache Hadoop",
  "Data Ingestion",
  "Data Transformation",
  "Data Analytics",
];

// Array 2
export const Topicarray2: string[] = [
  "Spark Core",
  "Structured Streaming",
  "Machine Learning",
  "Snowflake",
  "Data Warehousing",
  "ETL",
  "Data Modelling",
  "SQL",
  "Data Pipelines",
  "Cloud Data Warehousing",
  "Performance Tuning",
  "Data Integration",
  "Schema Design",
  "Data Storage",
  "Data Retrieval",
  "Scalability",
  "Data Governance",
  "Data Security",
];

// Array 3
export const Topicarray3: string[] = [
  "Data Lake",
  "Business Intelligence",
  "Analytics",
  "OLAP",
  "Data Architecture",
  "Python",
  "Data Wrangling",
  "Pandas",
  "NumPy",
  "Data Visualization",
  "Jupyter Notebooks",
  "Web Scraping",
  "APIs",
  "Data Cleaning",
  "Data Aggregation",
  "Data Transformation",
  "Matplotlib",
  "Seaborn",
];

// Array 4
export const Topicarray4: string[] = [
  "DataFrames",
  "Machine Learning",
  "Statistical Analysis",
  "Data Mining",
  "Scripting",
  "Automation",
  "Data Exploration",
  "SQL",
  "PostgreSQL",
  "Database Design",
  "Query Optimization",
  "Joins",
  "Subqueries",
  "CTE",
  "Window Functions",
  "Data Modelling",
  "Indexing",
  "Transactions",
];

// Array 5
export const Topicarray5: string[] = [
  "Stored Procedures",
  "Triggers",
  "Views",
  "Normalization",
  "Relational Databases",
  "Data Integrity",
  "Data Consistency",
  "Query Performance",
  "Schema Design",
  "Big Data",
  "Data Lakes",
  "Batch Processing",
  "Real-Time Processing",
  "Data Orchestration",
  "Workflow Automation",
  "Data Quality",
  "Data Lineage",
  "Metadata Management",
  "Data Catalogs",
  "Data Fabric",
  "Data Mesh",
  "Cloud Computing",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "DataOps",
  "Data Governance",
  "Data Security",
  "Scalability",
];
